'use client';

import { useMemo, useReducer, useState } from 'react';
import useSWR from 'swr';
import { AlertCircle, CheckCircle2, Save } from 'lucide-react';
import { fetchWithCsrf } from '@/lib/csrf';
import { fetchJson } from '@/lib/client-query';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import type { PortalSignInPolicy, SignInMethodState } from '@/lib/auth/sign-in-policy';

interface PolicyResponse { policy: PortalSignInPolicy; source: 'database' | 'legacy'; methods: SignInMethodState[]; revision: string | null; providerStatus?: { available: boolean; reason?: string } | null; error?: string; }
interface PolicyOverrides { policy: PortalSignInPolicy | null; methods: SignInMethodState[] | null; source: 'database' | 'legacy' | null; revision: string | null | undefined; providerStatus: PolicyResponse['providerStatus'] | undefined; }
type PolicyOverrideAction = { type: 'setPolicy'; policy: PortalSignInPolicy } | { type: 'saveResponse'; response: PolicyResponse };
const EMPTY_METHODS: SignInMethodState[] = [];
const EMPTY_OVERRIDES: PolicyOverrides = { policy: null, methods: null, source: null, revision: undefined, providerStatus: undefined };

function policyOverrideReducer(state: PolicyOverrides, action: PolicyOverrideAction): PolicyOverrides { return action.type === 'setPolicy' ? { ...state, policy: action.policy } : { policy: action.response.policy, methods: action.response.methods, source: action.response.source, revision: action.response.revision, providerStatus: action.response.providerStatus }; }
function enabledMethodPreview(policy: PortalSignInPolicy | null, methods: SignInMethodState[]) { if (!policy) return []; return methods.filter((method) => method.id === 'oidc' ? policy.methods.oidc.enabled : method.id === 'native_ad' ? policy.methods.nativeAd.enabled : policy.methods.local.enabled).map((method) => method.id === 'oidc' ? { ...method, displayName: policy.methods.oidc.displayName, description: policy.methods.oidc.description } : method); }
function policyWithMethodEnabled(policy: PortalSignInPolicy, methodId: SignInMethodState['id'], enabled: boolean): PortalSignInPolicy { return { ...policy, methods: { oidc: methodId === 'oidc' ? { ...policy.methods.oidc, enabled } : policy.methods.oidc, nativeAd: methodId === 'native_ad' ? { enabled } : policy.methods.nativeAd, local: methodId === 'local_break_glass' ? { enabled } : policy.methods.local } }; }
function policyWithOidcCopy(policy: PortalSignInPolicy, field: 'displayName' | 'description', value: string): PortalSignInPolicy { return { ...policy, methods: { ...policy.methods, oidc: { ...policy.methods.oidc, [field]: value } } }; }
function isMethodEnabled(policy: PortalSignInPolicy, methodId: SignInMethodState['id']) { return methodId === 'oidc' ? policy.methods.oidc.enabled : methodId === 'native_ad' ? policy.methods.nativeAd.enabled : policy.methods.local.enabled; }
function methodDisplayName(policy: PortalSignInPolicy, method: SignInMethodState) { return method.id === 'oidc' ? policy.methods.oidc.displayName : method.displayName; }
function providerProbeText(providerStatus: NonNullable<PolicyResponse['providerStatus']>) { return providerStatus.available ? 'Provider probe responding' : `Provider probe unavailable (${providerStatus.reason || 'unknown'})`; }

export default function SignInPanel() {
  const [overrides, dispatchOverrides] = useReducer(policyOverrideReducer, EMPTY_OVERRIDES); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<{ kind: 'error' | 'success'; text: string } | null>(null);
  const { data, error: loadError, isLoading } = useSWR<PolicyResponse>('/api/admin/config/sign-in', fetchJson, { revalidateOnFocus: false, revalidateOnReconnect: false });
  const policy = overrides.policy ?? data?.policy ?? null; const methods = overrides.methods ?? data?.methods ?? EMPTY_METHODS; const source = overrides.source ?? data?.source ?? 'legacy'; const providerStatus = overrides.providerStatus !== undefined ? overrides.providerStatus : data?.providerStatus ?? null;
  const revision = overrides.revision !== undefined ? overrides.revision : data?.revision ?? null; const enabledPreview = useMemo(() => enabledMethodPreview(policy, methods), [methods, policy]);
  const toggle = (methodId: SignInMethodState['id'], enabled: boolean) => { if (!policy) return; dispatchOverrides({ type: 'setPolicy', policy: policyWithMethodEnabled(policy, methodId, enabled) }); setMessage(null); };
  const save = async () => { if (!policy) return; setSaving(true); setMessage(null); try { const response = await fetchWithCsrf('/api/admin/config/sign-in', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ policy, reason: 'Updated portal sign-in policy', expectedRevision: revision }) }); const result = await response.json() as PolicyResponse; if (!response.ok) throw new Error(result.error || 'Unable to save sign-in policy.'); dispatchOverrides({ type: 'saveResponse', response: result }); setMessage({ kind: 'success', text: 'Sign-in policy saved.' }); } catch (error) { setMessage({ kind: 'error', text: error instanceof Error ? error.message : 'Unable to save sign-in policy.' }); } finally { setSaving(false); } };
  if (isLoading && !data) return <p aria-busy="true" className="text-sm text-muted-foreground">Loading sign-in policy…</p>;
  if (!policy) return <div role="alert" className="rounded-lg border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">{message?.text || (loadError instanceof Error ? loadError.message : 'Sign-in policy unavailable.')}</div>;
  return <SignInPolicyWorkspace policy={policy} methods={methods} source={source} providerStatus={providerStatus} enabledPreview={enabledPreview} saving={saving} message={message} onSave={() => void save()} onToggle={toggle} onCopyChange={(field, value) => dispatchOverrides({ type: 'setPolicy', policy: policyWithOidcCopy(policy, field, value) })} />;
}

function SignInPolicyWorkspace({ policy, methods, source, providerStatus, enabledPreview, saving, message, onSave, onToggle, onCopyChange }: { policy: PortalSignInPolicy; methods: SignInMethodState[]; source: 'database' | 'legacy'; providerStatus: PolicyResponse['providerStatus']; enabledPreview: SignInMethodState[]; saving: boolean; message: { kind: 'error' | 'success'; text: string } | null; onSave: () => void; onToggle: (method: SignInMethodState['id'], enabled: boolean) => void; onCopyChange: (field: 'displayName' | 'description', value: string) => void }) {
  return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-2xl font-semibold tracking-tight">Sign-in</h2><p className="mt-1 max-w-3xl text-sm text-muted-foreground">Choose which authorities the portal accepts. Credentials are submitted to exactly one selected authority.</p></div><Button onClick={onSave} disabled={saving || enabledPreview.length === 0} className="gap-2"><Save className="h-4 w-4" />{saving ? 'Saving…' : 'Save policy'}</Button></div>{message && <PolicyMessage message={message} />}{source === 'legacy' && <div className="rounded-lg border bg-muted/30 p-3 text-sm text-muted-foreground">This preview comes from legacy authentication settings. Saving creates the authoritative portal policy.</div>}<div className="rounded-lg border bg-muted/20 px-4 py-3 text-sm"><p className="font-medium text-foreground">Provider boundary</p><p className="mt-1 text-muted-foreground">SSO currently means the standalone auth service, which authenticates against Active Directory. Okta, Entra, and Keycloak are not hard-coded chooser options and cannot safely replace the issuer yet; they require an auth-service federation adapter with normalized claims, session expiry, and logout.</p></div><div className="grid gap-4 lg:grid-cols-[minmax(0,1.2fr)_minmax(18rem,0.8fr)]"><IdentitySources policy={policy} methods={methods} providerStatus={providerStatus} onToggle={onToggle} /><ChooserPreview methods={enabledPreview} /></div><OidcCopy policy={policy} onChange={onCopyChange} /></div>;
}

function PolicyMessage({ message }: { message: { kind: 'error' | 'success'; text: string } }) { return <div role={message.kind === 'error' ? 'alert' : 'status'} className={`flex gap-2 rounded-lg border p-3 text-sm ${message.kind === 'error' ? 'border-destructive/30 bg-destructive/5 text-destructive' : 'border-emerald-500/30 bg-emerald-500/5 text-foreground'}`}>{message.kind === 'error' ? <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" /> : <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />}<span>{message.text}</span></div>; }
function IdentitySources({ policy, methods, providerStatus, onToggle }: { policy: PortalSignInPolicy; methods: SignInMethodState[]; providerStatus: PolicyResponse['providerStatus']; onToggle: (method: SignInMethodState['id'], enabled: boolean) => void }) { return <Card><CardHeader><CardTitle className="text-base">Identity sources</CardTitle><CardDescription>Only ready sources can be enabled.</CardDescription></CardHeader><CardContent className="divide-y p-0">{methods.map((method) => <IdentitySource key={method.id} policy={policy} method={method} providerStatus={providerStatus} onToggle={onToggle} />)}</CardContent></Card>; }
function IdentitySource({ policy, method, providerStatus, onToggle }: { policy: PortalSignInPolicy; method: SignInMethodState; providerStatus: PolicyResponse['providerStatus']; onToggle: (method: SignInMethodState['id'], enabled: boolean) => void }) { const enabled = isMethodEnabled(policy, method.id); return <div className="flex gap-4 px-6 py-4"><Switch aria-label={`Enable ${method.displayName}`} checked={enabled} disabled={!method.ready && !enabled} onCheckedChange={(checked) => onToggle(method.id, checked)} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-x-3 gap-y-1"><p className="font-medium text-foreground">{methodDisplayName(policy, method)}</p><span className={`text-xs ${method.ready ? 'text-emerald-700 dark:text-emerald-400' : 'text-amber-700 dark:text-amber-400'}`}>{method.ready ? 'Ready' : 'Needs configuration'}</span></div>{method.readinessIssue && <p className="mt-1 text-xs leading-relaxed text-muted-foreground">{method.readinessIssue}</p>}{method.id === 'oidc' && method.ready && providerStatus && <p className="mt-1 text-xs text-muted-foreground">{providerProbeText(providerStatus)}</p>}</div></div>; }
function ChooserPreview({ methods }: { methods: SignInMethodState[] }) { return <Card><CardHeader><CardTitle className="text-base">Chooser preview</CardTitle><CardDescription>{methods.length === 1 ? 'The portal continues directly to this method.' : 'The portal shows this ordered list.'}</CardDescription></CardHeader><CardContent>{methods.length === 0 ? <p className="text-sm text-destructive">Enable at least one identity source.</p> : <div className="divide-y rounded-md border">{methods.map((method) => <div key={method.id} className="px-4 py-3"><p className="text-sm font-medium">{method.displayName}</p>{method.description && <p className="mt-0.5 text-xs leading-relaxed text-muted-foreground">{method.description}</p>}</div>)}</div>}</CardContent></Card>; }
function OidcCopy({ policy, onChange }: { policy: PortalSignInPolicy; onChange: (field: 'displayName' | 'description', value: string) => void }) { return <Card><CardHeader><CardTitle className="text-base">SSO chooser copy</CardTitle><CardDescription>Plain text shown on the portal chooser. Provider connection settings remain deployment-owned.</CardDescription></CardHeader><CardContent className="grid gap-4"><div className="space-y-2"><Label htmlFor="oidc-display-name">Display name</Label><Input id="oidc-display-name" minLength={1} maxLength={80} value={policy.methods.oidc.displayName} onChange={(event) => onChange('displayName', event.target.value)} /><p className="text-xs text-muted-foreground">1–80 characters</p></div><div className="space-y-2"><Label htmlFor="oidc-description">Description</Label><Input id="oidc-description" maxLength={200} value={policy.methods.oidc.description} onChange={(event) => onChange('description', event.target.value)} /><p className="text-xs text-muted-foreground">Up to 200 characters; rendered as plain text.</p></div></CardContent></Card>; }
