'use client';

import { useCallback, useEffect, useId, useState, type ReactNode } from 'react';
import { CircleHelp, FileArchive, Loader2, RefreshCw, Save, Users } from 'lucide-react';
import { fetchWithCsrf } from '@/lib/csrf';
import { ClientLocalDate } from '@/components/admin/ClientLocalDate';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import LdapPathInput from './LdapPathInput';

interface TicketGroup { id: string; dn: string; name: string; mail: string | null; canBeRequestedFor: boolean; canBeAssignee: boolean; canJoinViaTicket: boolean; autoApproveJoin: boolean; isActive: boolean; lastSyncedAt: string | null; lastSyncStatus: string | null; }
interface SyncRun { id: string; status: string; triggeredBy: string; startedAt: string; finishedAt: string | null; groupsProcessed: number; membersCaptured: number; }
interface GroupDraft { name: string; mail: string; canBeRequestedFor: boolean; canBeAssignee: boolean; canJoinViaTicket: boolean; autoApproveJoin: boolean; isActive: boolean; }
type AttachmentLimits = { maxFiles: string; maxFileMiB: string; maxTicketMiB: string };
const DEFAULT_ATTACHMENT_LIMITS: AttachmentLimits = { maxFiles: '50', maxFileMiB: '20', maxTicketMiB: '1024' };
const GROUP_OPTIONS: Array<[keyof Omit<GroupDraft, 'name' | 'mail'>, string, string]> = [
  ['canBeRequestedFor', 'Available as a ticket subject', 'Snapshot members may file a ticket about this group. Non-members cannot select it.'],
  ['canBeAssignee', 'Can be granted ticket access', 'Administrators may add this group to a ticket. Snapshot members can then view, reply to, and change that ticket\'s status, and the group becomes a notification target.'],
  ['canJoinViaTicket', 'Available for join requests', 'Users who are not current snapshot members may select this group when filing a request to join it.'],
  ['autoApproveJoin', 'Allow automatic join processing', 'Eligible join-ticket workflows may queue the directory membership change without manual approval. This only takes effect when join requests are also enabled.'],
  ['isActive', 'Active', 'Master switch for new use of this group. When off, the group disappears from new ticket forms, join requests, and assignment search. Existing ticket assignments remain active until an administrator removes them from those tickets.'],
];

function draftFor(group: TicketGroup): GroupDraft { return { name: group.name, mail: group.mail ?? '', canBeRequestedFor: group.canBeRequestedFor, canBeAssignee: group.canBeAssignee, canJoinViaTicket: group.canJoinViaTicket, autoApproveJoin: group.autoApproveJoin, isActive: group.isActive }; }

export default function TicketRoutingPanel() {
  const [groups, setGroups] = useState<TicketGroup[]>([]); const [runs, setRuns] = useState<SyncRun[]>([]); const [drafts, setDrafts] = useState<Record<string, GroupDraft>>({}); const [newDn, setNewDn] = useState(''); const [loading, setLoading] = useState(true); const [savingKey, setSavingKey] = useState<string | null>(null); const [syncing, setSyncing] = useState(false); const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null); const [attachmentLimits, setAttachmentLimits] = useState<AttachmentLimits>(DEFAULT_ATTACHMENT_LIMITS); const [savedAttachmentLimits, setSavedAttachmentLimits] = useState<AttachmentLimits>(DEFAULT_ATTACHMENT_LIMITS);
  const fetchGroups = useCallback(async () => { try { const [response, attachmentResponse] = await Promise.all([fetch('/api/admin/config/ticket-groups'), fetch('/api/admin/config/attachments')]); if (!response.ok) throw new Error('Failed to load ticket groups'); const result = await response.json(); const nextGroups: TicketGroup[] = result.groups ?? []; setGroups(nextGroups); setRuns(result.recentRuns ?? []); setDrafts(Object.fromEntries(nextGroups.map((group) => [group.dn, draftFor(group)]))); if (attachmentResponse.ok) { const attachmentData = await attachmentResponse.json(); const values = new Map((attachmentData.config ?? []).map((entry: { key: string; value: number }) => [entry.key, entry.value])); const next = { maxFiles: String(values.get('attachments.maxFiles') ?? 50), maxFileMiB: String(Number(values.get('attachments.maxFileBytes') ?? 20 * 1024 * 1024) / 1024 / 1024), maxTicketMiB: String(Number(values.get('attachments.maxTicketBytes') ?? 1024 * 1024 * 1024) / 1024 / 1024) }; setAttachmentLimits(next); setSavedAttachmentLimits(next); } } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'Failed to load' }); } finally { setLoading(false); } }, []);
  useEffect(() => { void fetchGroups(); }, [fetchGroups]);
  const saveGroup = async (dn: string) => { const draft = drafts[dn]; if (!draft) return; setSavingKey(dn); setMessage(null); try { const response = await fetchWithCsrf('/api/admin/config/ticket-groups', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ dn, name: draft.name, mail: draft.mail.trim() === '' ? null : draft.mail.trim(), canBeRequestedFor: draft.canBeRequestedFor, canBeAssignee: draft.canBeAssignee, canJoinViaTicket: draft.canJoinViaTicket, autoApproveJoin: draft.autoApproveJoin, isActive: draft.isActive }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Failed to save group'); setMessage({ type: 'success', text: `Saved "${draft.name}".` }); await fetchGroups(); } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'Failed to save' }); } finally { setSavingKey(null); } };
  const addGroup = async () => { if (!newDn.trim()) return; setSavingKey('__new__'); setMessage(null); try { const response = await fetchWithCsrf('/api/admin/config/ticket-groups', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ dn: newDn.trim() }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Failed to add group'); setNewDn(''); setMessage({ type: 'success', text: 'Group added. Run a sync to capture its membership.' }); await fetchGroups(); } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'Failed to add' }); } finally { setSavingKey(null); } };
  const runSync = async () => { setSyncing(true); setMessage(null); try { const response = await fetchWithCsrf('/api/admin/config/ticket-groups/sync', { method: 'POST' }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Directory sync failed'); setMessage({ type: result.outcome?.status === 'success' ? 'success' : 'error', text: `Sync ${result.outcome?.status}: ${result.outcome?.membersCaptured} members across ${result.outcome?.groupsProcessed} groups.` }); await fetchGroups(); } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'Sync failed' }); } finally { setSyncing(false); } };
  const saveAttachmentLimits = async () => { setSavingKey('__attachments__'); setMessage(null); try { const response = await fetchWithCsrf('/api/admin/config/attachments', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ values: { 'attachments.maxFiles': Number(attachmentLimits.maxFiles), 'attachments.maxFileBytes': Number(attachmentLimits.maxFileMiB) * 1024 * 1024, 'attachments.maxTicketBytes': Number(attachmentLimits.maxTicketMiB) * 1024 * 1024 } }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Failed to save attachment limits'); setSavedAttachmentLimits(attachmentLimits); setMessage({ type: 'success', text: 'Attachment limits saved.' }); } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'Failed to save attachment limits' }); } finally { setSavingKey(null); } };
  if (loading) return <div className="flex items-center justify-center py-8"><Loader2 className="h-6 w-6 animate-spin" /></div>;
  return <div className="space-y-4">{message && <Alert variant={message.type === 'error' ? 'destructive' : 'default'}><AlertDescription>{message.text}</AlertDescription></Alert>}<AttachmentPolicy limits={attachmentLimits} savedLimits={savedAttachmentLimits} saving={savingKey === '__attachments__'} onChange={setAttachmentLimits} onSave={saveAttachmentLimits} /><TicketGroups groups={groups} drafts={drafts} newDn={newDn} savingKey={savingKey} syncing={syncing} onNewDn={setNewDn} onAdd={() => void addGroup()} onSync={() => void runSync()} onDrafts={setDrafts} onSave={(dn) => void saveGroup(dn)} /><SyncHistory runs={runs} /></div>;
}

function AttachmentPolicy({ limits, savedLimits, saving, onChange, onSave }: { limits: AttachmentLimits; savedLimits: AttachmentLimits; saving: boolean; onChange: React.Dispatch<React.SetStateAction<AttachmentLimits>>; onSave: () => void }) {
  return <Card id="support-attachment-policy" className="scroll-mt-20 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><CardHeader><CardTitle className="flex items-center gap-2"><FileArchive className="h-5 w-5" /> Attachment policy</CardTitle><CardDescription>Runtime limits below stay inside fixed safety ceilings of 100 files, 20 MiB per file, 25 MiB per upload request, and 2 GiB per ticket. Every file is type-checked and malware-scanned before download.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-4 sm:grid-cols-3">{([['maxFiles', 'Files per ticket', '1–100'], ['maxFileMiB', 'MiB per file', '1–20'], ['maxTicketMiB', 'MiB per ticket', '1–2048']] as const).map(([key, label, hint]) => <div key={key} className="space-y-1.5"><Label htmlFor={`attachment-${key}`}>{label}</Label><Input id={`attachment-${key}`} type="number" min="1" value={limits[key]} onChange={(event) => onChange((previous) => ({ ...previous, [key]: event.target.value }))} /><p className="text-xs text-muted-foreground">{hint}</p></div>)}</div><div className="flex justify-end"><Button size="sm" disabled={saving || JSON.stringify(limits) === JSON.stringify(savedLimits)} onClick={onSave}>{saving ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Save className="mr-2 h-4 w-4" />}Save attachment policy</Button></div></CardContent></Card>;
}

function TicketGroups({ groups, drafts, newDn, savingKey, syncing, onNewDn, onAdd, onSync, onDrafts, onSave }: { groups: TicketGroup[]; drafts: Record<string, GroupDraft>; newDn: string; savingKey: string | null; syncing: boolean; onNewDn: (value: string) => void; onAdd: () => void; onSync: () => void; onDrafts: React.Dispatch<React.SetStateAction<Record<string, GroupDraft>>>; onSave: (dn: string) => void }) {
  return <Card id="approved-ticket-groups" className="scroll-mt-20 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><CardHeader><CardTitle className="flex items-center gap-2"><Users className="h-5 w-5" />Approved ticket groups</CardTitle><CardDescription>Approve Active Directory groups for ticket subjects, join requests, or staff assignments. These settings control eligibility; they do not grant ticket access by themselves. User-facing ticket forms read local snapshots and never query AD.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap items-end gap-2"><div className="flex-1 min-w-[280px] space-y-1.5"><div className="flex items-center gap-1"><Label htmlFor="new-group-dn">Add group by directory path</Label><InfoTooltip label="directory path">Select the group&apos;s unique Active Directory path. After adding it, set a short display name so staff and users never need to read the raw directory path.</InfoTooltip></div><LdapPathInput id="new-group-dn" suggestType="group" placeholder="CN=Ticket Team,OU=Groups,DC=example,DC=edu" value={newDn} onChange={onNewDn} /></div><Button size="sm" disabled={!newDn.trim() || savingKey === '__new__'} onClick={onAdd}>{savingKey === '__new__' && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}Add Group</Button><div className="space-y-1"><div className="flex items-center gap-1"><Button size="sm" variant="outline" disabled={syncing} onClick={onSync}>{syncing ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <RefreshCw className="h-4 w-4 mr-2" />}Pull membership from AD</Button><InfoTooltip label="Pull membership from AD">Runs one authorized directory refresh and replaces each successful group&apos;s local member snapshot, including member email addresses. The optional configured group email is not pulled from AD. A failed group keeps its previous snapshot. User-facing ticket forms keep reading the database and never contact AD. When enabled, the scheduler runs the same refresh hourly by default.</InfoTooltip></div><p className="text-xs text-muted-foreground max-w-sm">Refresh local group-member snapshots now. The enabled scheduler repeats this hourly by default; user-facing forms remain database-backed.</p></div></div>{groups.length === 0 && <p className="text-sm text-muted-foreground">No approved groups configured yet.</p>}{groups.map((group) => <GroupEditor key={group.id} group={group} draft={drafts[group.dn]} saving={savingKey === group.dn} onDrafts={onDrafts} onSave={onSave} />)}</CardContent></Card>;
}

function GroupEditor({ group, draft, saving, onDrafts, onSave }: { group: TicketGroup; draft: GroupDraft | undefined; saving: boolean; onDrafts: React.Dispatch<React.SetStateAction<Record<string, GroupDraft>>>; onSave: (dn: string) => void }) {
  if (!draft) return null;
  const dirty = JSON.stringify(draft) !== JSON.stringify(draftFor(group));
  const update = (change: Partial<GroupDraft>) => onDrafts((previous) => ({ ...previous, [group.dn]: { ...draft, ...change } }));
  return <div className="rounded-lg border p-4 space-y-3"><div className="flex flex-wrap items-center gap-2"><span className="font-medium">{group.name}</span>{!group.isActive && <Badge variant="secondary">inactive</Badge>}{group.lastSyncStatus === 'failed' && <Badge variant="destructive">sync failed</Badge>}{group.lastSyncedAt && <span className="text-xs text-muted-foreground">last synced <ClientLocalDate value={group.lastSyncedAt} /></span>}</div><p className="font-mono text-xs text-muted-foreground break-all">{group.dn}</p><div className="grid gap-3 sm:grid-cols-2"><GroupTextField id={`name-${group.id}`} label="Display name" help="The short, readable group name shown in ticket forms and the administrator access picker. The directory path remains the stored identity." value={draft.name} onChange={(name) => update({ name })} /><GroupTextField id={`mail-${group.id}`} label="Group email (optional)" help="Controls notification delivery only. When this group is assigned, the portal sends one copy to this address. If blank, it sends to enabled members from the latest local snapshot. This field does not grant ticket access." value={draft.mail} type="email" placeholder="ticket-team@example.org" onChange={(mail) => update({ mail })} /></div><div className="flex flex-wrap gap-4 text-sm">{GROUP_OPTIONS.map(([key, label, help]) => <span key={key} className="flex items-center gap-1"><label className="flex items-center gap-2"><input type="checkbox" checked={draft[key]} onChange={(event) => update({ [key]: event.target.checked })} className="h-4 w-4" />{label}</label><InfoTooltip label={label}>{help}</InfoTooltip></span>)}</div><div className="flex justify-end"><Button size="sm" disabled={!dirty || saving} onClick={() => onSave(group.dn)}>{saving ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <Save className="h-4 w-4 mr-2" />}Save Group</Button></div></div>;
}

function GroupTextField({ id, label, help, value, type = 'text', placeholder, onChange }: { id: string; label: string; help: string; value: string; type?: string; placeholder?: string; onChange: (value: string) => void }) { return <div className="space-y-1.5"><div className="flex items-center gap-1"><Label htmlFor={id}>{label}</Label><InfoTooltip label={label}>{help}</InfoTooltip></div><Input id={id} type={type} placeholder={placeholder} value={value} onChange={(event) => onChange(event.target.value)} /></div>; }
function SyncHistory({ runs }: { runs: SyncRun[] }) { return <Card><CardHeader><CardTitle className="text-base">Recent Directory Sync Runs</CardTitle><CardDescription>Snapshot refresh history with per-run outcomes.</CardDescription></CardHeader><CardContent>{runs.length === 0 ? <p className="text-sm text-muted-foreground">No sync runs recorded yet.</p> : <ul className="space-y-2 text-sm">{runs.map((run) => <li key={run.id} className="flex flex-wrap items-center gap-2"><Badge variant={run.status === 'success' ? 'default' : 'destructive'}>{run.status}</Badge><span><ClientLocalDate value={run.startedAt} /></span><span className="text-muted-foreground">by {run.triggeredBy} · {run.groupsProcessed} groups · {run.membersCaptured} members</span></li>)}</ul>}</CardContent></Card>; }
function InfoTooltip({ label, children }: { label: string; children: ReactNode }) { const id = useId(); return <span className="group/tooltip relative inline-flex shrink-0 align-middle"><button type="button" aria-label={`About ${label}`} aria-describedby={id} className="inline-flex h-5 w-5 cursor-help items-center justify-center rounded-full text-muted-foreground transition-colors hover:bg-muted hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><CircleHelp className="h-3.5 w-3.5" /></button><span id={id} role="tooltip" className="pointer-events-none invisible absolute bottom-full left-1/2 z-50 mb-2 w-72 -translate-x-1/2 rounded-md border border-border bg-popover px-3 py-2 text-left text-xs font-normal leading-relaxed text-popover-foreground opacity-0 shadow-lg transition-opacity group-hover/tooltip:visible group-hover/tooltip:opacity-100 group-focus-within/tooltip:visible group-focus-within/tooltip:opacity-100">{children}</span></span>; }
