apiVersion: v1
kind: Service
metadata:
  name: clamav
spec:
  type: ClusterIP
  selector:
    app: clamav
  ports:
  - name: tcp
    port: 3310
    targetPort: 3310
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: clamav
  template:
    metadata:
      labels:
        app: clamav
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: clamav
        image: clamav/clamav@sha256:f0954d679017eb6d48221e2b2be3ac5457bf278a844f39b672376f55a085f591
        ports:
        - containerPort: 3310
        resources:
          requests:
            cpu: 250m
            memory: 1536Mi
          limits:
            cpu: 1500m
            memory: 3Gi
        securityContext:
          allowPrivilegeEscalation: false
        startupProbe:
          tcpSocket:
            port: 3310
          failureThreshold: 120
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 3310
          periodSeconds: 10
        volumeMounts:
        - name: signatures
          mountPath: /var/lib/clamav
      volumes:
      - name: signatures
        persistentVolumeClaim:
          claimName: clamav-data
