import { Download, Filter, RefreshCw, Search } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { ClientLocalDate } from './ClientLocalDate';
import type { DataSourceFilter, OwnershipFilter, SyncFilter } from './AccountSyncStatusTypes';

interface AccountSyncStatusControlsProps {
  searchQuery: string; syncFilter: SyncFilter; dataSourceFilter: DataSourceFilter; ownershipFilter: OwnershipFilter; showAdvancedFilters: boolean;
  pageSize: number; shownAccounts: number; filteredAccounts: number; totalAccounts: number; isLoading: boolean;
  isPolling: boolean; lastUpdated: Date | null;
  onSearchChange: (value: string) => void; onSyncFilterChange: (value: SyncFilter) => void; onDataSourceFilterChange: (value: DataSourceFilter) => void; onOwnershipFilterChange: (value: OwnershipFilter) => void;
  onPageSizeChange: (value: number) => void; onToggleFilters: () => void; onTogglePolling: () => void; onRefresh: () => void; onExport: () => void;
}

export function AccountSyncStatusControls(props: AccountSyncStatusControlsProps) {
  return <Card><CardContent className="space-y-4 p-4"><div className="flex flex-col gap-4 lg:flex-row"><div className="relative flex-1"><Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" /><Input aria-label="Search sync status" type="text" placeholder="Search names, usernames, request, batch item, or batch run IDs..." value={props.searchQuery} onChange={(event) => props.onSearchChange(event.target.value)} className="pl-8" /></div><div className="flex flex-wrap items-center gap-2"><div className="flex h-10 items-center gap-2 rounded-lg border border-border bg-muted/50 px-3 py-1.5"><div className={`h-2 w-2 rounded-full ${props.isPolling ? 'animate-pulse bg-green-500' : 'bg-muted-foreground'}`} /><span className="text-xs text-muted-foreground">{props.isPolling ? 'Live updates' : 'Paused'}</span><div className="mx-1 h-4 w-px bg-border" /><Button type="button" variant="link" onClick={props.onTogglePolling} className="h-auto p-0 text-xs font-medium">{props.isPolling ? 'Pause' : 'Resume'}</Button></div>{props.lastUpdated && <span className="mr-2 hidden text-xs text-muted-foreground xl:inline-block">Updated: <ClientLocalDate value={props.lastUpdated} format="time" /></span>}<Button type="button" onClick={props.onRefresh} disabled={props.isLoading} className="gap-2"><RefreshCw className={`h-4 w-4 ${props.isLoading ? 'animate-spin' : ''}`} />Refresh</Button><Button type="button" variant="outline" onClick={props.onExport} className="gap-2"><Download className="h-4 w-4" />Export CSV</Button><Button type="button" variant="secondary" onClick={props.onToggleFilters} className="gap-2"><Filter className="h-4 w-4" />{props.showAdvancedFilters ? 'Hide' : 'Show'} Filters</Button></div></div>
    {props.showAdvancedFilters && <div className="grid grid-cols-1 gap-4 rounded-lg bg-muted/50 p-4 md:grid-cols-3"><FilterSelect id="sync-status-filter" label="Sync Status" value={props.syncFilter} onValueChange={props.onSyncFilterChange} options={[['all', 'All Statuses'], ['fully_synced', 'Fully Synced'], ['partial_sync', 'Partial Sync'], ['ad_only', 'AD Only'], ['vpn_only', 'VPN Only'], ['request_only', 'Request Only'], ['offboarded', 'Offboarded'], ['orphaned', 'Orphaned'], ['issues', 'Has Issues']]} /><FilterSelect id="sync-source-filter" label="Data Source" value={props.dataSourceFilter} onValueChange={props.onDataSourceFilterChange} options={[['all', 'All Sources'], ['has_ad', 'Has AD Account'], ['has_vpn', 'Has VPN Account'], ['has_request', 'Has Access Request'], ['missing_ad', 'Missing AD'], ['missing_vpn', 'Missing VPN'], ['missing_request', 'Missing Request']]} /><FilterSelect id="sync-ownership-filter" label="Portal ownership" value={props.ownershipFilter} onValueChange={props.onOwnershipFilterChange} options={[['all', 'All ownership states'], ['request_owner', 'Access request'], ['batch_owner', 'Batch account'], ['no_owner', 'No portal owner'], ['needs_review', 'Needs review'], ['ownership_unavailable', 'Ownership unavailable']]} /></div>}
    <div className="flex items-center justify-between pt-2 text-sm text-muted-foreground"><span>Showing {props.shownAccounts} of {props.filteredAccounts} accounts{props.filteredAccounts !== props.totalAccounts && ` (filtered from ${props.totalAccounts} total)`}</span><div className="flex items-center gap-2"><Label htmlFor="sync-status-page-size">Per page:</Label><Select value={String(props.pageSize)} onValueChange={(value) => props.onPageSizeChange(Number(value))}><SelectTrigger id="sync-status-page-size" className="h-8 w-[70px]"><SelectValue placeholder="25" /></SelectTrigger><SelectContent>{[10, 25, 50, 100].map((size) => <SelectItem key={size} value={String(size)}>{size}</SelectItem>)}</SelectContent></Select></div></div>
  </CardContent></Card>;
}

function FilterSelect<T extends string>({ id, label, value, onValueChange, options }: { id: string; label: string; value: T; onValueChange: (value: T) => void; options: Array<[T, string]> }) {
  return <div className="space-y-2"><Label htmlFor={id}>{label}</Label><Select value={value} onValueChange={(next) => onValueChange(next as T)}><SelectTrigger id={id} className="bg-card"><SelectValue placeholder={`Select ${label.toLowerCase()}`} /></SelectTrigger><SelectContent>{options.map(([optionValue, optionLabel]) => <SelectItem key={optionValue} value={optionValue}>{optionLabel}</SelectItem>)}</SelectContent></Select></div>;
}
