import { Button } from '@/components/ui/button';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { AccountSyncStatusBadge } from './AccountSyncStatusBadge';
import { AccountOwnershipDetails } from './AccountOwnershipDetails';
import type { SortDirection, SyncSortField, SyncStatusAccount } from './AccountSyncStatusTypes';

interface AccountSyncStatusTableProps { accounts: SyncStatusAccount[]; currentPage: number; totalPages: number; sortField: SyncSortField; sortDirection: SortDirection; onSort: (field: SyncSortField) => void; onPageChange: (page: number) => void; onAccountSelect: (account: SyncStatusAccount) => void; }

export function AccountSyncStatusTable({ accounts, currentPage, totalPages, sortField, sortDirection, onSort, onPageChange, onAccountSelect }: AccountSyncStatusTableProps) {
  const sortMark = (field: SyncSortField) => sortField === field ? (sortDirection === 'asc' ? ' ↑' : ' ↓') : '';
  return <div className="overflow-x-auto rounded-md border bg-card"><Table className="min-w-[1050px]"><TableHeader className="bg-muted/50"><TableRow><SortableHead field="identifier" className="w-[200px]" onSort={onSort}>Identifier{sortMark('identifier')}</SortableHead><SortableHead field="name" onSort={onSort}>Name{sortMark('name')}</SortableHead><TableHead>Email</TableHead><SortableHead field="syncStatus" onSort={onSort}>Sync Status{sortMark('syncStatus')}</SortableHead><TableHead>AD</TableHead><TableHead>VPN</TableHead><TableHead>Portal owner</TableHead><TableHead>Issues</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{accounts.map((account) => <TableRow key={account.accountRef ?? account.identifier} className="hover:bg-muted/50"><TableCell className="font-medium"><div className="text-sm font-medium text-foreground">{account.identifier}</div>{account.wasAutoAssigned && <span className="text-xs text-blue-600 dark:text-blue-400">Auto-assigned</span>}</TableCell><TableCell>{account.name}</TableCell><TableCell className="text-muted-foreground">{account.email || <span>—</span>}</TableCell><TableCell><AccountSyncStatusBadge status={account.syncStatus} /></TableCell><TableCell><AccountPresence present={account.hasAdAccount} primary={account.adUsername} secondary={account.adDisplayName} /></TableCell><TableCell><AccountPresence present={account.hasVpnAccount} primary={account.vpnUsername} secondary={account.vpnPortalType} /></TableCell><TableCell className="min-w-[12rem]"><AccountOwnershipDetails ownership={account.ownership} compact /></TableCell><TableCell>{account.syncIssues.length > 0 ? <div className="text-xs text-red-600 dark:text-red-400">{account.syncIssues.length} issue{account.syncIssues.length === 1 ? '' : 's'}</div> : <span className="text-sm text-muted-foreground">—</span>}</TableCell><TableCell><Button type="button" variant="link" onClick={() => onAccountSelect(account)} className="h-auto p-0 font-medium text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-300">View details</Button></TableCell></TableRow>)}</TableBody></Table>{totalPages > 1 && <div className="flex items-center justify-between border-t p-4"><Button type="button" variant="outline" size="sm" onClick={() => onPageChange(Math.max(1, currentPage - 1))} disabled={currentPage === 1}>Previous</Button><span className="text-sm text-foreground">Page {currentPage} of {totalPages}</span><Button type="button" variant="outline" size="sm" onClick={() => onPageChange(Math.min(totalPages, currentPage + 1))} disabled={currentPage === totalPages}>Next</Button></div>}</div>;
}

function SortableHead({ field, className = '', onSort, children }: { field: SyncSortField; className?: string; onSort: (field: SyncSortField) => void; children: React.ReactNode }) { return <TableHead onClick={() => onSort(field)} className={`cursor-pointer hover:bg-muted ${className}`}>{children}</TableHead>; }
function AccountPresence({ present, primary, secondary }: { present: boolean; primary: string | null; secondary: string | null }) { return present ? <div className="text-sm"><div className="whitespace-nowrap font-medium text-green-600 dark:text-green-400">✓ {primary}</div><div className="text-xs text-muted-foreground">{secondary}</div></div> : <span className="text-sm text-muted-foreground">—</span>; }
