import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { ClientLocalDate } from './ClientLocalDate';
import { AccountSyncStatusBadge } from './AccountSyncStatusBadge';
import { AccountOwnershipDetails } from './AccountOwnershipDetails';
import type { SyncStatusAccount } from './AccountSyncStatusTypes';

interface AccountSyncStatusDetailDialogProps { account: SyncStatusAccount | null; open: boolean; onOpenChange: (open: boolean) => void; }

export function AccountSyncStatusDetailDialog({ account, open, onOpenChange }: AccountSyncStatusDetailDialogProps) {
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle className="text-2xl font-bold">Account Sync Details</DialogTitle></DialogHeader>{account && <div className="space-y-6"><IdentitySection account={account} /><AccountOwnershipDetails ownership={account.ownership} /><DirectorySection account={account} /><VpnSection account={account} /><RequestSection account={account} /><IssuesSection issues={account.syncIssues} /></div>}</DialogContent></Dialog>;
}

function IdentitySection({ account }: { account: SyncStatusAccount }) { return <DetailSection title="Identity"><DetailRow label="Identifier" value={<span className="font-mono">{account.identifier}</span>} /><DetailRow label="Name" value={account.name} /><DetailRow label="Email" value={account.email} /><DetailRow label="Sync Status" value={<AccountSyncStatusBadge status={account.syncStatus} />} /></DetailSection>; }
function DirectorySection({ account }: { account: SyncStatusAccount }) { return <DetailSection title="Active Directory">{account.hasAdAccount ? <><DetailRow label="Status" value={<span className={account.adAccountEnabled ? 'font-medium text-green-600 dark:text-green-400' : 'font-medium text-slate-600 dark:text-slate-300'}>{account.adAccountEnabled ? '✓ Enabled' : 'Disabled'}</span>} /><DetailRow label="Username" value={<span className="font-mono">{account.adUsername}</span>} /><DetailRow label="Display Name" value={account.adDisplayName} /><DetailRow label="Email" value={account.adEmail} />{account.adSyncDate && <DetailRow label="Last Synced" value={<ClientLocalDate value={account.adSyncDate} />} />}</> : <MissingDetail label={missingSystemLabel(account, 'AD', 'Active Directory')} />}</DetailSection>; }
function VpnSection({ account }: { account: SyncStatusAccount }) { return <DetailSection title="VPN Access">{account.hasVpnAccount ? <><DetailRow label="Status" value={<span className={account.vpnStatus === 'active' ? 'font-medium text-green-600 dark:text-green-400' : 'font-medium text-slate-600 dark:text-slate-300'}>{account.vpnStatus === 'active' ? '✓ Active' : account.vpnStatus || 'Unknown'}</span>} /><DetailRow label="Username" value={<span className="font-mono">{account.vpnUsername}</span>} /><DetailRow label="Portal Type" value={account.vpnPortalType} /><DetailRow label="Account Status" value={account.vpnStatus} />{account.vpnCreatedAt && <DetailRow label="Created" value={<ClientLocalDate value={account.vpnCreatedAt} />} />}</> : <MissingDetail label={missingSystemLabel(account, 'VPN', 'VPN access')} />}</DetailSection>; }
function RequestSection({ account }: { account: SyncStatusAccount }) { return <DetailSection title="Access Request">{account.hasAccessRequest ? <><DetailRow label="Status" value={<span className="font-medium text-green-600 dark:text-green-400">✓ Exists</span>} /><DetailRow label="Request ID" value={<span className="font-mono">{account.requestId}</span>} /><DetailRow label="Request Status" value={account.requestStatus} /><DetailRow label="Manually Assigned" value={account.isManuallyAssigned ? 'Yes' : 'No'} />{account.requestCreatedAt && <DetailRow label="Created" value={<ClientLocalDate value={account.requestCreatedAt} />} />}</> : <MissingDetail label={account.ownership?.ownerType === 'batch_account' ? 'Not part of this batch' : 'Not present'} />}</DetailSection>; }
function IssuesSection({ issues }: { issues: string[] }) { const uniqueIssues = [...new Set(issues)]; return uniqueIssues.length > 0 ? <div><h3 className="mb-3 text-lg font-semibold text-red-900 dark:text-red-200">Sync Issues</h3><div className="rounded-lg border border-red-200 bg-red-50 p-4 dark:border-red-900 dark:bg-red-950/40"><ul className="list-inside list-disc space-y-1">{uniqueIssues.map((issue) => <li key={issue} className="text-sm text-red-800 dark:text-red-200">{issue}</li>)}</ul></div></div> : null; }
function DetailSection({ title, children }: { title: string; children: React.ReactNode }) { return <div><h3 className="mb-3 text-lg font-semibold text-foreground">{title}</h3><div className="space-y-2 rounded-lg bg-muted/50 p-4">{children}</div></div>; }
function DetailRow({ label, value }: { label: string; value: React.ReactNode }) { return <div className="flex justify-between gap-4"><span className="text-sm font-medium text-muted-foreground">{label}:</span><span className="text-right text-sm text-foreground">{value ?? <span className="text-muted-foreground">—</span>}</span></div>; }
function missingSystemLabel(account: SyncStatusAccount, system: 'AD' | 'VPN', fallback: string): string {
  return account.ownership?.ownerType === 'batch_account'
    && account.ownership.expectedSystems?.includes(system) === false
    ? 'Not part of this batch'
    : `${fallback} not present`;
}
function MissingDetail({ label }: { label: string }) { return <div className="text-sm text-muted-foreground">{label}</div>; }
