'use client';

import { CornerDownLeft, Search } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { CommandDialog, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList, CommandSeparator } from '@/components/ui/command';
import type { AdminNavItem, AdminNavSection } from '@/lib/admin/navigation';

type NavigationLoadState = 'loading' | 'ready' | 'error';

export function AdminShellCommandPalette({ open, onOpenChange, state, error, sections, destinations, itemsById, onRetry, onNavigate, isModuleDisabled }: { open: boolean; onOpenChange: (open: boolean) => void; state: NavigationLoadState; error: string | null; sections: AdminNavSection[]; destinations: ReturnType<typeof import('@/lib/admin/navigation').getVisibleAdminNavDestinations>; itemsById: ReadonlyMap<string, AdminNavItem>; onRetry: () => void; onNavigate: (href: string) => void; isModuleDisabled: (item: AdminNavItem) => boolean }) {
  return <CommandDialog open={open} onOpenChange={onOpenChange} title="Jump to an admin section" description="Search the sections available to your account" className="overflow-hidden border-border/80 shadow-2xl sm:max-w-xl"><div className="border-b border-border bg-muted/35 px-4 pb-3 pt-4"><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-primary">Quick navigation</p><p className="mt-1 text-sm text-muted-foreground">Search the admin tools available to your account.</p></div><CommandInput placeholder={state === 'ready' ? 'Type a page or capability…' : 'Navigation is loading…'} className="h-12" disabled={state !== 'ready'} /><CommandList className="max-h-[420px] px-1 py-2"><CommandStatus state={state} error={error} onRetry={onRetry} />{state === 'ready' && <CommandEmpty><div className="px-6 py-8"><Search className="mx-auto mb-3 h-5 w-5 text-muted-foreground" /><p className="font-medium text-foreground">No matching section</p><p className="mt-1 text-xs">Try a page name such as tickets, users, or workflows.</p></div></CommandEmpty>}{state === 'ready' && sections.map((section, index) => <SectionGroup key={section.id} section={section} preceding={index > 0} onNavigate={onNavigate} isModuleDisabled={isModuleDisabled} />)}{state === 'ready' && destinations.length > 0 && <DestinationGroup destinations={destinations} itemsById={itemsById} onNavigate={onNavigate} />}</CommandList><div className="flex items-center justify-between border-t border-border bg-muted/30 px-4 py-2 text-[11px] text-muted-foreground"><span className="inline-flex items-center gap-1.5"><CornerDownLeft className="h-3 w-3" /> Open</span><span>Esc to close</span></div></CommandDialog>;
}

function CommandStatus({ state, error, onRetry }: { state: NavigationLoadState; error: string | null; onRetry: () => void }) { if (state === 'loading') return <div className="px-6 py-8 text-center text-sm text-muted-foreground">Loading navigation…</div>; if (state !== 'error') return null; return <div role="alert" className="px-6 py-8 text-center"><p className="font-medium text-foreground">Navigation is unavailable</p><p className="mt-1 text-xs text-muted-foreground">{error}</p><Button type="button" variant="outline" size="sm" className="mt-3" onClick={onRetry}>Try again</Button></div>; }
function SectionGroup({ section, preceding, onNavigate, isModuleDisabled }: { section: AdminNavSection; preceding: boolean; onNavigate: (href: string) => void; isModuleDisabled: (item: AdminNavItem) => boolean }) { return <div>{preceding && <CommandSeparator />}<CommandGroup heading={section.label}>{section.items.map((item) => { const Icon = item.icon; const disabled = isModuleDisabled(item); return <CommandItem key={item.id} value={`${item.label} ${item.description} ${item.id}`} onSelect={() => onNavigate(item.href)} disabled={disabled} className="gap-3 rounded-lg px-3 py-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md border border-border bg-background"><Icon className="h-4 w-4" /></span><span className="flex min-w-0 flex-col"><span className="font-medium">{item.label}</span><span className="truncate text-xs text-muted-foreground">{disabled ? 'Module disabled' : item.description}</span></span></CommandItem>; })}</CommandGroup></div>; }
function DestinationGroup({ destinations, itemsById, onNavigate }: { destinations: ReturnType<typeof import('@/lib/admin/navigation').getVisibleAdminNavDestinations>; itemsById: ReadonlyMap<string, AdminNavItem>; onNavigate: (href: string) => void }) { return <><CommandSeparator /><CommandGroup heading="Sections & controls">{destinations.map((destination) => { const parent = itemsById.get(destination.parentId); if (!parent) return null; const Icon = parent.icon; return <CommandItem key={destination.id} value={`${parent.label} ${destination.label} ${destination.description} ${destination.keywords.join(' ')} ${destination.id}`} onSelect={() => onNavigate(destination.href)} className="gap-3 rounded-lg px-3 py-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md border border-primary/20 bg-primary/5 text-primary"><Icon className="h-4 w-4" /></span><span className="flex min-w-0 flex-1 flex-col"><span className="truncate text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{parent.label}</span><span className="font-medium">{destination.label}</span><span className="truncate text-xs text-muted-foreground">{destination.description}</span></span></CommandItem>; })}</CommandGroup></>; }
