import DateTimePicker from '@/components/DateTimePicker';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectGroup, SelectItem, SelectLabel, SelectTrigger, SelectValue } from '@/components/ui/select';
import { ChevronDown, Search, SlidersHorizontal, X } from 'lucide-react';
import { useState } from 'react';
import { activeLogFilterCount, normalizeLogFilterValue } from './LogsHelpers';
import type { LogFilters } from './LogsTypes';

interface LogsFiltersProps {
  filters: LogFilters;
  onFiltersChange: (filters: LogFilters) => void;
  limit: number;
  onLimitChange: (limit: number) => void;
  onClear: () => void;
}

function FilterField({ label, labelId, children }: { label: string; labelId: string; children: React.ReactNode }) {
  return <div className="space-y-1.5"><span id={labelId} className="text-sm font-medium text-muted-foreground">{label}</span>{children}</div>;
}

export function LogsFilters({ filters, onFiltersChange, limit, onLimitChange, onClear }: LogsFiltersProps) {
  const [advancedOpen, setAdvancedOpen] = useState(false);
  const activeCount = activeLogFilterCount(filters);
  const updateFilter = (field: keyof LogFilters, value: string) => onFiltersChange({ ...filters, [field]: normalizeLogFilterValue(value) });

  return <Card className="gap-0 py-0 shadow-sm"><CardContent className="p-4 sm:p-5">
    <div className="flex flex-col gap-3 xl:flex-row xl:items-end">
      <div className="relative min-w-0 flex-1 xl:max-w-md"><label htmlFor="logs-search" className="sr-only">Search audit logs</label><Search aria-hidden="true" className="pointer-events-none absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input id="logs-search" type="search" value={filters.search} onChange={(event) => updateFilter('search', event.target.value)} placeholder="Search actions, people, targets, or details" className="pl-9" /></div>
      <FilterField label="Category" labelId="logs-category-label"><Select value={filters.category || 'all'} onValueChange={(value) => updateFilter('category', value)}><SelectTrigger aria-labelledby="logs-category-label" className="w-full xl:w-44"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All categories</SelectItem><SelectItem value="navigation">Navigation</SelectItem><SelectItem value="access_request">Access request</SelectItem><SelectItem value="event">Event</SelectItem><SelectItem value="user">User</SelectItem><SelectItem value="group">Group</SelectItem><SelectItem value="batch">Batch</SelectItem><SelectItem value="vpn">VPN</SelectItem><SelectItem value="support">Support</SelectItem><SelectItem value="blocklist">Blocklist</SelectItem><SelectItem value="settings">Settings</SelectItem><SelectItem value="logs">Logs</SelectItem><SelectItem value="lifecycle">Lifecycle</SelectItem><SelectItem value="sync_status">Sync status</SelectItem><SelectItem value="session">Session</SelectItem><SelectItem value="search">Search</SelectItem></SelectContent></Select></FilterField>
      <FilterField label="Outcome" labelId="logs-outcome-label"><Select value={filters.outcome || 'all'} onValueChange={(value) => updateFilter('outcome', value)}><SelectTrigger aria-labelledby="logs-outcome-label" className="w-full xl:w-40"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All outcomes</SelectItem><SelectItem value="success">Success</SelectItem><SelectItem value="failure">Failure</SelectItem><SelectItem value="denied">Denied</SelectItem><SelectItem value="pending">Pending</SelectItem><SelectItem value="rollback">Rollback</SelectItem><SelectItem value="skipped">Skipped</SelectItem></SelectContent></Select></FilterField>
      <div className="flex items-center gap-2 xl:pb-0.5"><Button type="button" variant="outline" size="sm" onClick={onClear} disabled={activeCount === 0} className="gap-1.5"><X aria-hidden="true" className="h-3.5 w-3.5" />Clear{activeCount > 0 ? ` (${activeCount})` : ''}</Button></div>
    </div>
    <Collapsible open={advancedOpen} onOpenChange={setAdvancedOpen} className="mt-3 border-t pt-3"><CollapsibleTrigger className="inline-flex items-center gap-1.5 rounded-md px-1 py-1 text-sm font-medium text-muted-foreground transition-colors hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" aria-label="Toggle advanced filters"><SlidersHorizontal aria-hidden="true" className="h-4 w-4" />More filters{activeCount > 0 ? ` · ${activeCount} active` : ''}<ChevronDown aria-hidden="true" className={`h-4 w-4 transition-transform ${advancedOpen ? 'rotate-180' : ''}`} /></CollapsibleTrigger>
      <CollapsibleContent><div className="grid grid-cols-1 gap-3 pt-4 sm:grid-cols-2 xl:grid-cols-4">
        <FilterField label="Actor name or username" labelId="logs-username-label"><Input aria-labelledby="logs-username-label" value={filters.username} onChange={(event) => updateFilter('username', event.target.value)} placeholder="Name or username" /></FilterField>
        <FilterField label="Action" labelId="logs-action-label"><Select value={filters.action || 'all'} onValueChange={(value) => updateFilter('action', value)}><SelectTrigger aria-labelledby="logs-action-label" className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All actions</SelectItem><SelectGroup><SelectLabel>Navigation</SelectLabel><SelectItem value="view_page">View page</SelectItem><SelectItem value="switch_tab">Switch tab</SelectItem><SelectItem value="admin_logout">Admin logout</SelectItem></SelectGroup><SelectGroup><SelectLabel>Access requests</SelectLabel><SelectItem value="view_request">View request</SelectItem><SelectItem value="approve_request">Approve request</SelectItem><SelectItem value="reject_request">Reject request</SelectItem><SelectItem value="acknowledge_request">Acknowledge request</SelectItem><SelectItem value="create_account">Create account</SelectItem><SelectItem value="send_to_faculty">Send to faculty</SelectItem></SelectGroup><SelectGroup><SelectLabel>VPN management</SelectLabel><SelectItem value="create_vpn_account">Create VPN account</SelectItem><SelectItem value="update_vpn_account">Update VPN account</SelectItem><SelectItem value="disable_vpn_account">Disable VPN account</SelectItem><SelectItem value="enable_vpn_account">Enable VPN account</SelectItem></SelectGroup><SelectGroup><SelectLabel>User management</SelectLabel><SelectItem value="view_user">View user</SelectItem><SelectItem value="update_user">Update user</SelectItem><SelectItem value="disable_user">Disable user</SelectItem><SelectItem value="enable_user">Enable user</SelectItem></SelectGroup><SelectGroup><SelectLabel>Group management</SelectLabel><SelectItem value="add_group_member">Add group member</SelectItem><SelectItem value="remove_group_member">Remove group member</SelectItem></SelectGroup><SelectGroup><SelectLabel>Lifecycle</SelectLabel><SelectItem value="create_lifecycle_action">Create action</SelectItem><SelectItem value="process_lifecycle_action">Process action</SelectItem><SelectItem value="cancel_lifecycle_action">Cancel action</SelectItem></SelectGroup><SelectGroup><SelectLabel>Settings</SelectLabel><SelectItem value="update_settings">Update settings</SelectItem><SelectItem value="toggle_login">Toggle login</SelectItem><SelectItem value="toggle_registration">Toggle registration</SelectItem></SelectGroup></SelectContent></Select></FilterField>
        <FilterField label="Execution status" labelId="logs-status-label"><Select value={filters.success || 'all'} onValueChange={(value) => updateFilter('success', value)}><SelectTrigger aria-labelledby="logs-status-label" className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem><SelectItem value="true">Succeeded</SelectItem><SelectItem value="false">Failed</SelectItem></SelectContent></Select></FilterField>
        <FilterField label="Target type" labelId="logs-target-label"><Select value={filters.targetType || 'all'} onValueChange={(value) => updateFilter('targetType', value)}><SelectTrigger aria-labelledby="logs-target-label" className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All targets</SelectItem><SelectItem value="AccessRequest">Access request</SelectItem><SelectItem value="VPNAccount">VPN account</SelectItem><SelectItem value="User">User</SelectItem><SelectItem value="Event">Event</SelectItem><SelectItem value="SupportTicket">Support ticket</SelectItem><SelectItem value="BatchAccountCreation">Batch creation</SelectItem><SelectItem value="BlockedEmail">Blocked email</SelectItem><SelectItem value="AccountLifecycleAction">Lifecycle action</SelectItem><SelectItem value="Group">Group</SelectItem><SelectItem value="Settings">Settings</SelectItem></SelectContent></Select></FilterField>
        <FilterField label="Event kind" labelId="logs-event-label"><Select value={filters.eventKind || 'all'} onValueChange={(value) => updateFilter('eventKind', value)}><SelectTrigger aria-labelledby="logs-event-label" className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All event kinds</SelectItem><SelectItem value="read">Read</SelectItem><SelectItem value="write">Write</SelectItem><SelectItem value="security">Security</SelectItem><SelectItem value="notification">Notification</SelectItem><SelectItem value="lifecycle">Lifecycle</SelectItem><SelectItem value="sync">Sync</SelectItem><SelectItem value="system">System</SelectItem></SelectContent></Select></FilterField>
        <DateTimePicker label="From" value={filters.startDate} onChange={(value) => updateFilter('startDate', value)} placeholder="Start date/time" /><DateTimePicker label="To" value={filters.endDate} onChange={(value) => updateFilter('endDate', value)} placeholder="End date/time" />
        <FilterField label="Rows" labelId="logs-limit-label"><Select value={String(limit)} onValueChange={(value) => onLimitChange(Number(value))}><SelectTrigger aria-labelledby="logs-limit-label" className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="25">25 rows</SelectItem><SelectItem value="50">50 rows</SelectItem><SelectItem value="100">100 rows</SelectItem><SelectItem value="200">200 rows</SelectItem></SelectContent></Select></FilterField>
      </div></CollapsibleContent>
    </Collapsible>
  </CardContent></Card>;
}
