import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { RichTextEditor } from '@/components/support/RichTextEditor';
import RichTextContent from '@/components/support/RichTextContent';
import { ClientLocalDate } from './ClientLocalDate';
import { isEmptyRichText } from '@/lib/ticket-content';
import type { SupportTicket } from './TicketDetailTypes';

export function TicketDetailConversation({ ticket, value, onChange, onSubmit, onClear, isSubmitting, uploadingFiles, onImageFiles }: { ticket: SupportTicket; value: string; onChange: (value: string) => void; onSubmit: () => void; onClear: () => void; isSubmitting: boolean; uploadingFiles: boolean; onImageFiles?: (files: File[]) => void }) {
  return <div className="min-w-0 space-y-6 p-5 sm:p-6 lg:overflow-y-auto lg:pb-8"><section><h3 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-3">Original Message</h3><div className="bg-muted/50 p-5 rounded-lg border border-border"><RichTextContent content={ticket.body} /></div></section><section><h3 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-3">Responses ({ticket.responses.length})</h3>{ticket.responses.length === 0 ? <p className="text-muted-foreground text-center py-6 bg-muted/50 rounded-lg border border-dashed border-border text-sm">No responses yet</p> : <div className="space-y-3">{ticket.responses.map((response) => <div key={response.id} className="rounded-lg border p-4"><div className="mb-2.5 flex justify-between gap-2"><span className="font-semibold text-sm">{response.author}{response.isStaff && <Badge variant="secondary" className="ml-2">Staff</Badge>}</span><span className="text-xs text-muted-foreground"><ClientLocalDate value={response.createdAt} /></span></div><RichTextContent content={response.message} /></div>)}</div>}</section>{ticket.status !== 'closed' && <section className="border-t border-border pt-4"><h3 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-3">Add Response</h3><RichTextEditor value={value} onChange={onChange} disabled={isSubmitting || uploadingFiles} ariaLabel="Type your response here" onImageFiles={onImageFiles} /><p className="text-xs text-muted-foreground mt-2 mb-3">Paste or drag screenshots straight into the editor to attach them.</p><div className="flex justify-end gap-2"><Button onClick={onClear} variant="ghost" size="sm">Clear</Button><Button onClick={onSubmit} disabled={isSubmitting || uploadingFiles || isEmptyRichText(value)} size="sm">{isSubmitting ? 'Submitting...' : 'Submit Response'}</Button></div></section>}</div>;
}
