import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { ExternalLink } from 'lucide-react';
import { ticketCategoryLabel } from '@/lib/support/ticket-categories';
import { ClientLocalDate } from './ClientLocalDate';
import { formatTicketStatus, ticketSeverityClass, ticketStatusClass, type SupportTicket } from './TicketDetailTypes';

export function TicketDetailHeader({ ticket, isUpdating, onStatus }: { ticket: SupportTicket; isUpdating: boolean; onStatus: (status: string) => void }) {
  return <DialogHeader className="border-b bg-muted/30 px-5 py-4 pr-12 sm:px-6"><div className="flex flex-col items-start justify-between gap-4 sm:flex-row"><div className="flex-1 space-y-3 min-w-0"><div className="flex gap-2 flex-wrap"><Badge variant="outline" className={ticketStatusClass(ticket.status)}>{formatTicketStatus(ticket.status)}</Badge>{ticket.category && <Badge variant="outline">{ticketCategoryLabel(ticket.category)}</Badge>}{ticket.severity && <Badge variant="outline" className={ticketSeverityClass(ticket.severity)}>{ticket.severity.toUpperCase()}</Badge>}</div><DialogTitle className="text-xl font-bold text-foreground leading-snug">{ticket.subject}</DialogTitle><div className="flex items-center gap-3 flex-wrap text-sm text-muted-foreground"><span className="inline-flex items-center gap-1.5"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-primary/10 text-[11px] font-bold text-primary">{ticket.username.charAt(0).toUpperCase()}</span><span className="font-medium text-foreground">{ticket.username}</span></span><span className="font-mono text-xs">#{ticket.id.slice(0, 8)}</span><ClientLocalDate value={ticket.createdAt} />{ticket.requestedForGroupDn && <span className="font-mono text-xs truncate max-w-[220px]" title={ticket.requestedForGroupDn}>for {ticket.requestedForGroupDn}</span>}</div></div><div className="flex shrink-0 flex-wrap gap-2 sm:flex-col"><Button asChild variant="ghost" size="sm"><a href={`/admin/support/tickets/${ticket.id}`}><ExternalLink className="h-4 w-4" /> Full case</a></Button>{ticket.status !== 'in_progress' && ticket.status !== 'closed' && <Button onClick={() => onStatus('in_progress')} disabled={isUpdating} size="sm">Start Progress</Button>}<Button onClick={() => onStatus(ticket.status === 'closed' ? 'open' : 'closed')} disabled={isUpdating} size="sm" variant={ticket.status === 'closed' ? 'default' : 'outline'}>{ticket.status === 'closed' ? 'Reopen' : 'Close Ticket'}</Button></div></div></DialogHeader>;
}
