import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import type { AccessRequest } from './RequestDetailTypes';

interface RequestManualAssignmentPanelProps {
  request: AccessRequest | null;
  open: boolean;
  linkedAdUsername: string;
  linkedVpnUsername: string;
  manualAssignmentNotes: string;
  adUsernameCheckMessage: string;
  vpnUsernameCheckMessage: string;
  onClose: () => void;
  onLinkedAdUsernameChange: (value: string) => void;
  onLinkedVpnUsernameChange: (value: string) => void;
  onManualAssignmentNotesChange: (value: string) => void;
  onCheckAdUsernameExists: () => void;
  onCheckVpnUsernameExists: () => void;
  onSubmit: () => void;
}

export default function RequestManualAssignmentPanel({ request, open, linkedAdUsername, linkedVpnUsername, manualAssignmentNotes, adUsernameCheckMessage, vpnUsernameCheckMessage, onClose, onLinkedAdUsernameChange, onLinkedVpnUsernameChange, onManualAssignmentNotesChange, onCheckAdUsernameExists, onCheckVpnUsernameExists, onSubmit }: RequestManualAssignmentPanelProps) {
  return <Dialog open={open} onOpenChange={(open) => { if (!open) { onClose(); } }}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>Manual Assignment to Existing Account</DialogTitle></DialogHeader><div className="space-y-4">
    <div className="p-4 bg-blue-50 dark:bg-blue-950/40 border border-blue-200 dark:border-blue-900 rounded-lg"><div className="flex items-start gap-2"><svg className="w-5 h-5 text-blue-600 dark:text-blue-400 shrink-0 mt-0.5" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" /></svg><div className="text-sm text-blue-900 dark:text-blue-200"><p className="font-semibold mb-1">About Manual Assignment</p><p>Use this feature when the user already has an existing Active Directory account{!request?.isInternal && ' or VPN access'}. This will link their access request to the existing account without creating a new one.</p></div></div></div>
    <div><label htmlFor="linked-ad-username" className="block text-sm font-medium text-muted-foreground mb-2">Existing Active Directory Username *</label><div className="flex gap-2"><input id="linked-ad-username" type="text" value={linkedAdUsername} onChange={(e) => onLinkedAdUsernameChange(e.target.value)} className="flex-1 px-3 py-2 border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500" placeholder="Enter existing AD username" /><button onClick={onCheckAdUsernameExists} className="px-4 py-2 bg-primary text-primary-foreground hover:bg-primary/90 rounded-lg text-sm font-semibold">Verify</button></div>{adUsernameCheckMessage && <p className={`text-sm mt-1 ${adUsernameCheckMessage?.includes('exists') ? 'text-green-600 dark:text-green-400' : 'text-red-600 dark:text-red-400'}`}>{adUsernameCheckMessage}</p>}<p className="text-xs text-muted-foreground mt-1">{request?.isInternal ? 'For internal users, this will link to their existing @cpp.edu account' : 'Enter the Active Directory username that already exists for this user'}</p></div>
    {!request?.isInternal && <div><label htmlFor="linked-vpn-username" className="block text-sm font-medium text-muted-foreground mb-2">Existing VPN Username (Optional)</label><div className="flex gap-2"><input id="linked-vpn-username" type="text" value={linkedVpnUsername} onChange={(e) => onLinkedVpnUsernameChange(e.target.value)} className="flex-1 px-3 py-2 border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500" placeholder="Enter existing VPN username (if different from AD)" />{linkedVpnUsername.trim() && <button onClick={onCheckVpnUsernameExists} className="px-4 py-2 bg-primary text-primary-foreground hover:bg-primary/90 rounded-lg text-sm font-semibold">Verify</button>}</div>{vpnUsernameCheckMessage && <p className={`text-sm mt-1 ${vpnUsernameCheckMessage?.includes('exists') ? 'text-green-600 dark:text-green-400' : 'text-red-600 dark:text-red-400'}`}>{vpnUsernameCheckMessage}</p>}<p className="text-xs text-muted-foreground mt-1">Leave blank if the VPN username is the same as the AD username</p></div>}
    <div><label htmlFor="manual-assignment-notes" className="block text-sm font-medium text-muted-foreground mb-2">Assignment Notes (Optional)</label><textarea id="manual-assignment-notes" value={manualAssignmentNotes} onChange={(e) => onManualAssignmentNotesChange(e.target.value)} rows={3} className="w-full px-3 py-2 border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500" placeholder="Add any notes about why this account is being manually assigned..." /></div>
    <div className="p-3 bg-yellow-50 dark:bg-yellow-950/40 border border-yellow-200 dark:border-yellow-900 rounded-lg"><div className="flex items-start gap-2"><svg className="w-5 h-5 text-yellow-600 dark:text-yellow-400 shrink-0 mt-0.5" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" /></svg><div className="text-sm text-yellow-900 dark:text-yellow-200"><p className="font-semibold mb-1">Important</p><p>This will approve the request and link it to the existing account. Make sure the username is correct before proceeding.{request?.isInternal ? ' For internal users, the AD account description will be updated but the existing email will be preserved.' : ' The user\'s email and name will be updated in the VPN account if it exists.'}</p></div></div></div>
    <div className="flex justify-end gap-3"><button onClick={onClose} className="px-4 py-2 text-muted-foreground bg-muted rounded-lg hover:bg-muted transition-colors">Cancel</button><button onClick={onSubmit} disabled={!linkedAdUsername.trim() || !adUsernameCheckMessage?.includes('exists')} className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed">Link to Existing Account</button></div>
  </div></DialogContent></Dialog>;
}
