apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: uar-dev-infra
  namespace: flux-system
  labels:
    uar.dev/release: 75d1d298e4bcb4f37bba7ff958d3952fd35e283b
spec:
  interval: 1m
  retryInterval: 30s
  path: ./release/75d1d298e4bcb4f37bba7ff958d3952fd35e283b/infra
  prune: true
  sourceRef:
    kind: GitRepository
    name: uar-dev
  serviceAccountName: uar-dev-reconciler
  timeout: 25m
  wait: true
  commonMetadata:
    labels:
      uar.dev/release: 75d1d298e4bcb4f37bba7ff958d3952fd35e283b
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: uar-dev-migrations
  namespace: flux-system
  labels:
    uar.dev/release: 75d1d298e4bcb4f37bba7ff958d3952fd35e283b
spec:
  interval: 1m
  retryInterval: 30s
  path: ./release/75d1d298e4bcb4f37bba7ff958d3952fd35e283b/migrations
  prune: false
  sourceRef:
    kind: GitRepository
    name: uar-dev
  serviceAccountName: uar-dev-reconciler
  timeout: 35m
  wait: true
  commonMetadata:
    labels:
      uar.dev/release: 75d1d298e4bcb4f37bba7ff958d3952fd35e283b
  dependsOn:
  - name: uar-dev-infra
    readyExpr: has(dep.status) && has(dep.status.conditions) && dep.metadata.labels['uar.dev/release']
      == self.metadata.labels['uar.dev/release'] && dep.status.conditions.exists(c,
      c.type == 'Ready' && c.status == 'True') && dep.metadata.generation == dep.status.observedGeneration
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: uar-dev-apps
  namespace: flux-system
  labels:
    uar.dev/release: 75d1d298e4bcb4f37bba7ff958d3952fd35e283b
spec:
  interval: 1m
  retryInterval: 30s
  path: ./release/75d1d298e4bcb4f37bba7ff958d3952fd35e283b/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: uar-dev
  serviceAccountName: uar-dev-reconciler
  timeout: 25m
  wait: true
  commonMetadata:
    labels:
      uar.dev/release: 75d1d298e4bcb4f37bba7ff958d3952fd35e283b
  dependsOn:
  - name: uar-dev-migrations
    readyExpr: has(dep.status) && has(dep.status.conditions) && dep.metadata.labels['uar.dev/release']
      == self.metadata.labels['uar.dev/release'] && dep.status.conditions.exists(c,
      c.type == 'Ready' && c.status == 'True') && dep.metadata.generation == dep.status.observedGeneration
