'use client';
import * as m from 'framer-motion/m';
import { Info } from 'lucide-react';
import { RichTextEditor } from '@/components/support/RichTextEditor';
import { isEmptyRichText } from '@/lib/ticket-content';
import { cn } from '@/lib/utils';
import type { TicketFormField, TicketFormValues } from '@/lib/support/ticket-form-schema';
import type { TicketDraft } from './CreateTicketTypes';
import { TicketStructuredFields } from './CreateTicketStructuredFields';
const severities = [{ value: 'low', label: 'Low', blurb: 'Minor, can wait' }, { value: 'medium', label: 'Medium', blurb: 'Moderate impact' }, { value: 'high', label: 'High', blurb: 'Significant impact' }, { value: 'critical', label: 'Critical', blurb: 'System down' }];
function descriptionAriaLabel(wantsGroupJoin: boolean, topic: { value: string } | null): string {
  if (wantsGroupJoin) return 'Why do you need this group? Include any approval or context that helps reviewers';
  if (topic?.value === 'INFRASTRUCTURE') return 'What happened, since when, and what is the user impact?';
  return 'Please provide a detailed description of your issue or request';
}
function guidanceFor(draft: TicketDraft, wantsGroupJoin: boolean, topic: { value: string; label: string } | null, joinWorkflowAvailable: boolean): string {
  if (wantsGroupJoin) return joinWorkflowAvailable ? 'An automation workflow is configured for group joins: once submitted, your membership request is queued automatically.' : 'A staff member will review and approve your membership request.';
  if (draft.severity === 'critical') return 'Critical tickets page the on-call rotation in addition to standard routing - please include current impact and start time.';
  if (topic?.value === 'INFRASTRUCTURE') return 'Infrastructure issues route to platform staff. Attach screenshots or error output as evidence on the right.';
  return topic ? `${topic.label} tickets are tracked with a unique ID. You and assigned staff can follow up in the ticket thread.` : '';
}
export function TicketDetailsPane({ draft, setDraft, subjectTouched, setSubjectTouched, formFields, values, setValues, missingFieldKeySet, wantsGroupJoin, selectedTopic, joinWorkflowAvailable, toggleSeverity, onImageFiles }: { draft: TicketDraft; setDraft: React.Dispatch<React.SetStateAction<TicketDraft>>; subjectTouched: boolean; setSubjectTouched: React.Dispatch<React.SetStateAction<boolean>>; formFields: TicketFormField[]; values: TicketFormValues; setValues: React.Dispatch<React.SetStateAction<TicketFormValues>>; missingFieldKeySet: Set<string>; wantsGroupJoin: boolean; selectedTopic: { value: string; label: string } | null; joinWorkflowAvailable: boolean; toggleSeverity: (severity: string) => void; onImageFiles: (files: File[]) => void }) {
  const hasStructuredAnswer = Object.values(values).some((value) => value.trim());
  const descriptionLabel = descriptionAriaLabel(wantsGroupJoin, selectedTopic);
  const guidance = guidanceFor(draft, wantsGroupJoin, selectedTopic, joinWorkflowAvailable);
  return <m.section initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.35, delay: 0.05 }} aria-label="Ticket details" className="space-y-6 rounded-xl border border-border bg-card p-5 shadow-sm sm:p-6"><div className="space-y-5"><div className="rounded-lg border border-border bg-background p-4"><p className="mb-3 text-xs font-semibold uppercase tracking-wider text-muted-foreground">1 · Summary</p><label htmlFor="subject" className="mb-2 block text-sm font-medium text-foreground">Subject <span className="text-destructive">*</span></label><input type="text" id="subject" required value={draft.subject} onChange={(event) => { setSubjectTouched(true); setDraft((current) => ({ ...current, subject: event.target.value })); }} className="w-full rounded-lg border border-input bg-background px-4 py-2.5 text-foreground focus:ring-2 focus:ring-ring" placeholder="Brief description of your issue" maxLength={200} />{!subjectTouched && draft.subject && <p className="mt-1 text-xs text-muted-foreground">Suggested from your topic — edit it if you&apos;d like.</p>}</div><fieldset className="rounded-lg border border-border bg-muted/20 p-4"><p className="mb-3 text-xs font-semibold uppercase tracking-wider text-muted-foreground">2 · Impact</p><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{severities.map((option) => <button key={option.value} type="button" aria-pressed={draft.severity === option.value} onClick={() => toggleSeverity(option.value)} className={cn('rounded-lg border px-3 py-2 text-center transition-all', draft.severity === option.value ? 'border-primary bg-primary text-primary-foreground shadow-sm' : 'border-border bg-card hover:border-muted-foreground/40 hover:bg-accent/40')}><span className="block text-sm font-semibold">{option.label}</span><span className="block text-xs">{option.blurb}</span></button>)}</div></fieldset></div><TicketStructuredFields fields={formFields} values={values} setValues={setValues} missing={missingFieldKeySet} category={draft.category} /><div className="rounded-lg border border-border bg-background p-4"><p className="mb-3 text-xs font-semibold uppercase tracking-wider text-muted-foreground">{formFields.length ? '4' : '3'} · Description</p><label htmlFor="body" className="mb-2 block text-sm font-medium text-foreground">Description {!isEmptyRichText(draft.narrative) || !hasStructuredAnswer ? <span className="text-destructive">*</span> : <span className="font-normal text-muted-foreground">(structured answers already added)</span>}</label><RichTextEditor value={draft.narrative} onChange={(html) => setDraft((current) => ({ ...current, narrative: html }))} onImageFiles={onImageFiles} ariaLabel={descriptionLabel} /></div>{guidance && <div className="flex items-start gap-3 rounded-lg border border-border bg-muted/40 p-4"><Info className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" /><p className="text-xs leading-relaxed text-muted-foreground">{guidance}</p></div>}</m.section>;
}
