apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clamav-data
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: uar-dev-local
  resources:
    requests:
      storage: 1Gi
