apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uar-dev
resources:
- asset-store.yaml
- auth.yaml
- clamav.yaml
- monitor-probe.yaml
- portal.yaml
- runtime-config.yaml
configMapGenerator:
- name: asset-store-config
  files:
  - nginx.conf
generatorOptions:
  disableNameSuffixHash: false
