apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uar-dev
resources:
- job.yaml
configMapGenerator:
- name: uar-release-migration
  files:
  - bootstrap-roles.sql
  - run-release.cjs
