'use client';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import type { MonitorCredentialDraft } from './workflowPanelTypes';

export function MonitorCredentialForm({ credentialDraft, credentialBusy, onChange, onCreate }: { credentialDraft: MonitorCredentialDraft; credentialBusy: boolean; onChange: (draft: MonitorCredentialDraft) => void; onCreate: () => void }) {
  return <details className="rounded border"><summary className="cursor-pointer px-2 py-1.5 text-xs font-medium">Add host-bound credential</summary><div className="space-y-2 border-t p-2"><label className="block space-y-1 text-xs"><span>Credential name</span><Input value={credentialDraft.name} onChange={(event) => onChange({ ...credentialDraft, name: event.target.value })} /></label><label className="block space-y-1 text-xs"><span>Credential type</span><select className="h-9 w-full rounded-md border bg-background px-2 text-xs" value={credentialDraft.kind} onChange={(event) => onChange({ ...credentialDraft, kind: event.target.value })}><option value="bearer">Bearer token</option><option value="http_basic">HTTP Basic</option><option value="secret_header">Secret header</option><option value="ldap_bind">LDAP bind</option></select></label>{(credentialDraft.kind === 'http_basic' || credentialDraft.kind === 'ldap_bind') && <label className="block space-y-1 text-xs"><span>{credentialDraft.kind === 'ldap_bind' ? 'Bind DN' : 'Username'}</span><Input value={credentialDraft.username} onChange={(event) => onChange({ ...credentialDraft, username: event.target.value })} /></label>}{credentialDraft.kind === 'secret_header' && <label className="block space-y-1 text-xs"><span>Header name</span><Input value={credentialDraft.headerName} onChange={(event) => onChange({ ...credentialDraft, headerName: event.target.value })} /></label>}<label className="block space-y-1 text-xs"><span>Secret</span><Input type="password" autoComplete="new-password" value={credentialDraft.secret} onChange={(event) => onChange({ ...credentialDraft, secret: event.target.value })} /></label><label className="block space-y-1 text-xs"><span>Exact allowed hosts</span><textarea rows={2} className="flex w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm" value={credentialDraft.hosts} onChange={(event) => onChange({ ...credentialDraft, hosts: event.target.value })} placeholder="service.example.edu, 10.0.0.12" /></label><Button type="button" size="sm" onClick={onCreate} disabled={credentialBusy}>{credentialBusy ? 'Saving…' : 'Save credential'}</Button></div></details>;
}
